### ISSUE TITLE
Upgrading to 1.39.8 Ironbank

### ISSUE THREAD

**Issue by fishpeopleapps** [CanastaWiki/Canasta#418]
## Describe the situation
**Summary**: Multiple issues when attempting to upgrade to newer canasta version using Ironbank's hardened image resulting in broken staging environment, incorrect permission, etc. 

**Description**: Hello! I am the developer on the Space-Wiki. We recently attempted to update to PHP 8.1 and the new hardened image (https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fcanastawiki%252Fcanasta) tag 1.39.7. We started this process back in April and continue to have problems so any insight, at all, would be greatly appreciated. Initially our hosting company said we had to use a custom image, due to this error: https://hub.docker.com/_/php. Our "custom image" consists of the Ironbank canasta's image and manually installed required packages. 

The custom image seems to "work" but these are some of the errors that appear in ArgoCD's logs:

**Screenshots**: 
`rsync: [generator] failed to set times on "/mediawiki/images": Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
rm -rf /mw_origin_files
rm: cannot remove /mw_origin_files: Permission denied`

`++ find /maintenance-scripts/ -maxdepth 1 -mindepth 1 -type f -name '*.sh'
stat: cannot statx '/mediawiki/sitemap': No such file or directory`

`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.90.109. Set the 'ServerName' directive globally to suppress this message
[15-Jul-2024 21:44:33] ERROR: failed to open error_log (/var/log/php8.1-fpm.log): Permission denied (13)
[15-Jul-2024 21:44:33] ERROR: failed to post process the configuration
[15-Jul-2024 21:44:33] ERROR: FPM initialization failed`

`Warning: wikis.yaml does not exist. Running general jobs.`

Here's the full log: [argoCDLogs.txt](https://github.com/user-attachments/files/16255905/argoCDLogs.txt)

Final Thoughts --
By posting here I am hoping for a friendly wiki person to please point me in the correct direction of anything I might find useful for understanding what's going on so I can fix the problem. I noticed a lot of changes between run-all and run-apache. Is there a reason we cannot use run-apache or this file was changed? 

**Steps to reproduce the issue** (if applicable):
n/a

## Expected behavior
According to Ironbank and our hosting company, nothing is wrong, so I imagine to them the expected behavior is that the upgrade went smoothly and everything functions normally. 

## System info
_Please complete the following information:_
 - MediaWiki version (e.g. 1.39.7) - 1.39.1 trying to upgrade to 1.39.7
 - Canasta version - whatever comes with that image
 - Host operating system - linux
 - Do you have sudo/root permissions on the host OS? no

## Sanity checks
Only applies to troubleshooting requests.

- Have you checked the documentation on canasta.wiki for how to address this? Yes
- Have you checked prior issues on GitHub yet? Yes
- Are you following all Canasta approaches and have **_avoided_** doing things such as running `docker exec` directly on the container, removing the Caddy/Varnish containers, adding unauthorized files to the Docker container after startup, etc.? IDK

Thank you for your help and expertise, it is greatly appreciated.

**Comment by fishpeopleapps** [comment]
No apologies needed, thank you so much for your time! This issue has been ongoing since 22/April so I am incredibly grateful for any insight you can offer.

I inquired about sudo/root permissions and this was the response I received: 
Hosting Company: As I recall, the image has root permissions already for the apache config scripts, so I'd think the script can be run as root instead of the non-root user
Ironbank: The base container from Iron Bank is setup to run as root (as apache changes to a non-root user on its own). The cluster also has to be configured (usually via security policy) to allow privileged containers (preferably on dedicated nodes with no other workloads, etc).
Hosting Company: The container is currently allowed to run as root in the cluster. 

I wanted to add a couple of things as well. 
1. We have not been able to pull down our staging environment locally. We can pull the wiki image via docker desktop and look around, using the 'exec' tab for commands, but that is the extend. We can add commands to either the apache script* or as args in our deployment.yaml file. 
2. *We previously pulled out the run-all.sh script and mounted it outside of Ironbank so we could run commands/scripts in the run_autoupdate(), but yesterday I thought maybe returning to a baseline and using the Ironbank image with as little deviation as possible might be best for troubleshooting. I have attached the updated error log after I made this change:
[baselineArgoLogs.txt](https://github.com/user-attachments/files/16313374/baselineArgoLogs.txt)

Here is the contents of the deployment.yaml file - 
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-wiki
spec:
  template:
    spec:
      containers:
      - name: space-wiki
        command: ['/bin/sh']
        args:
            - '-c'
            - |
              echo "Running apache script"
              /run-all.sh
              echo "run all complete" 
      volumes:
      - name: config-script
        configMap:
          name: local-settings-staging`

**Comment by fishpeopleapps** [comment]
Thoughts on this error in the logs? 
`PHP Fatal error:  Declaration of GetMediawikiSettings::finalSetup() must be compatible with Maintenance::finalSetup(?MediaWiki\Settings\SettingsBuilder $settingsBuilder = null) in /getMediawikiSettings.php on line 142`

Brought it up to Ironbank and they aren't sure but are open to test/change things.

**Comment by yaronkoren** [comment]
@fishpeopleapps - sorry for the long delay. That was apparently a bug in Canasta, which was fixed in [this commit](https://github.com/CanastaWiki/Canasta/commit/06e3949ac95c8db389ab6258604b9e7903653001). Maybe it works better now, with the latest code?

**Comment by fishpeopleapps** [comment]
@yaronkoren That did fix the php issue. I noticed Ironbank didn't include skins.yaml and extensions-skins.php in their hardened image. They were able to add extensions-skins.php, but not the skins.yaml because 
"While skins.yaml is in the github, the file does not exist in the upstream container.  I ran "find / -name skins.yaml" inside the upstream container and it did not return any results.  I also used grep to search for any references in files/scripts to that file and again, there were no hits."

Right now we have this error and I am wondering if it could be related to not having the skins.yaml file in the upstream container? 
Fatal error: Uncaught Exception: Unable to open file /var/www/mediawiki/w/skins/chameleon/skin.json: filemtime(): stat failed for /var/www/mediawiki/w/skins/chameleon/skin.json in /var/www/mediawiki/w/includes/registration/ExtensionRegistry.php:199 Stack trace: #0 /var/www/mediawiki/w/includes/GlobalFunctions.php(86): ExtensionRegistry->queue() #1 /mediawiki/config/LocalSettings.php(476): wfLoadSkin() #2 /var/www/mediawiki/w/CanastaDefaultSettings.php(82): require_once('...') #3 /var/www/mediawiki/w/LocalSettings.php(8): require_once('...') #4 /var/www/mediawiki/w/includes/Setup.php(218): require_once('...') #5 /var/www/mediawiki/w/includes/WebStart.php(86): require_once('...') #6 /var/www/mediawiki/w/index.php(44): require('...') #7 {main} thrown in /var/www/mediawiki/w/includes/registration/ExtensionRegistry.php on line 199

**Comment by yaronkoren** [comment]
@fishpeopleapps - Sorry again for the delay. Are they using the latest version of Canasta? skins.yaml is right [here](https://github.com/CanastaWiki/Canasta/blob/master/_sources/configs/skins.yaml).

**Comment by fishpeopleapps** [comment]
@yaronkoren 
we are using the hardened image from ironbank which is 1.39.8 and the source code can be found here: https://repo1.dso.mil/dsop/opensource/canastawiki/canasta

When I pointed out that file and how its missing their response was - 
"While skins.yaml is in the github, the file does not exist in the upstream container. I ran "find / -name skins.yaml" inside the upstream container and it did not return any results. I also used grep to search for any references in files/scripts to that file and again, there were no hits."

**Comment by fishpeopleapps** [comment]
In the hardening_manifest.yaml

```
apiVersion: v1

name: opensource/canastawiki/canasta

tags:
  - "1.39.8"
  - "latest"

args:
  BASE_IMAGE: "opensource/debian/debian"
  BASE_TAG: "12.6"

labels:
  org.opencontainers.image.title: "canastawiki/canasta"
  org.opencontainers.image.description: "Canasta is an all-in-one MediaWiki package for sysadmins that makes it easy to manage MediaWiki, add extensions, and load starter content and data structures."
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.url: "https://github.com/CanastaWiki/Canasta"
  org.opencontainers.image.vendor: "Canasta"
  org.opencontainers.image.version: "1.39.8"
  mil.dso.ironbank.image.keywords: "opensource,canasta,canastawiki,debian,php,mediawiki"
  mil.dso.ironbank.image.type: "opensource"
  mil.dso.ironbank.product.name: "opensource/canastawiki/canasta"

resources:
- tag: ghcr.io/canastawiki/canasta:1.39.8-latest
  url: docker://ghcr.io/canastawiki/canasta@sha256:68e823d715231b35b1348f200d797aad45aa6ee7c488031ec45de7d721015cc1
```
