### ISSUE TITLE
localhost not resolving correctly leading to 502 error

### ISSUE THREAD

**Issue by silverhikari** [CanastaWiki/Canasta#441]
## Describe the bug
**Summary**: problem with localhost not resolving correctly

**Description**: running docker compose script, and after doing fixes such as creating /mediawiki, try running the script and review compose logs reports that apache can not servername and defaults to some random ip from 172.20.0.2 to 172.20.0.6. setting `ServerName localhost` in apache.conf did not work(add via volumes)(caused the used random ip to list a varnish cache error). also tried disabling caddy but that changed nothing.

**Steps to reproduce the behavior**:
1. create mediawiki dir and add volumes link `./mediawiki:/mediawiki` under web in override
2. Run `docker compose up -d`
3. open webpage to `localhost:80`
4. see error 502

## System info
_Please complete the following information:_
 - MediaWiki version: 1.39.8
 - Canasta version: 2.0.1

**Comment by silverhikari** [comment]
## .ENV

```
PORT=80
HTTPS_PORT=443
MYSQL_PASSWORD=mediawiki
MW_SITE_SERVER=https://localhost
MW_SITE_FQDN=localhost
PHP_UPLOAD_MAX_FILESIZE=10M
PHP_POST_MAX_SIZE=10M
PHP_MAX_INPUT_VARS=1000
MW_SITEMAP_SUBDIR=
MW_SITEMAP_IDENTIFIER=mediawiki
USE_EXTERNAL_DB=false
```

## docker-compose.override.yml

```
# The above version is the Docker Compose manifest's version, not the Canasta Docker Compose stack's version.
#
# --- Canasta Stack for Docker Compose ---
#
# If you need to make changes to the stack, make them here.
# Only edits to docker-compose.override.yml are officially supported by Canasta.
#
# Uncomment the commented services and add lines below them if you would like to make additional customizations to them.
services:
  #db:
  web:
    image: ghcr.io/canastawiki/canasta:2.0.1
    volumes:
        - ./mediawiki:/mediawiki
        # - ./apache2.conf:/etc/apache2/apache2.conf
  #elasticsearch:
  #caddy:
  #varnish:
```
